server:
  port: 8112
spring:
  application:
    name: bdp-basic
  datasource:
    url: jdbc:oracle:thin:@bjjgq.ticp.net:1521:orcl
    username: ztwzjt
    password: ztwzjt
    driverClassName: oracle.jdbc.OracleDriver
  jpa:
    database: oracle
    properties:
       hibernate:
          dialect: org.hibernate.dialect.Oracle10gDialect
          show_sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/      #服务注册中信地址，含有BASIC认证的用户名和密码
  instance:
    prefer-ip-address: true         #将IP注册到服务注册中心