server:
   port: 8106
spring: 
   application: 
      name: bdp-crm
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/      #服务注册中信地址，含有BASIC认证的用户名和密码
  instance:
    prefer-ip-address: true         #将IP注册到服务注册中心