package org.bdp.basic.entity.mapper;

import javax.persistence.*;

/**
 * AbstractBasicOrg generated by MyEclipse Persistence Tools
 */
@MappedSuperclass
public abstract class AbstractBasicOrg implements java.io.Serializable {

    /**  */
    private static final long serialVersionUID = 1L;
    // Fields
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "basic_org_seq")
    @SequenceGenerator(sequenceName = "basic_org_seq", allocationSize = 1, name = "basic_org_seq")
    private Long orgId;

    @Column(name = "member_Code")
    private String memberCode;

    @Column(name = "org_Code")
    private String orgCode;

    @Column(name = "org_Parent")
    private String orgParent;

    @Column(name = "org_Name")
    private String orgName;

    @Column(name = "org_Abbreviate")
    private String orgAbbreviate;

    @Column(name = "org_Phone")
    private String orgPhone;

    @Column(name = "org_Fax")
    private String orgFax;

    @Column(name = "org_Corporation")
    private String orgCorporation;

    @Column(name = "org_Accounts")
    private String orgAccounts;

    @Column(name = "org_Bankname")
    private String orgBankname;

    @Column(name = "org_Tanu")
    private String orgTanu;

    @Column(name = "org_Addr")
    private String orgAddr;

    @Column(name = "org_Remark")
    private String orgRemark;

    @Column(name = "org_Isleaf")
    private Long orgIsleaf;

    @Column(name = "org_Nodecode")
    private String orgNodecode;

    @Column(name = "basic_Share")
    private Long basicShare;

    @Column(name = "company_Code")
    private String companyCode;

    @Column(name = "org_Sign")
    private Long orgSign;

    @Column(name = "org_Signratio")
    private Double orgSignratio;

    @Column(name = "org_Mark")
    private String orgMark;

    @Column(name = "share_Itemcode")
    private String shareItemcode;

    @Column(name = "share_Orgcode")
    private String shareOrgcode;

    @Column(name = "print_Authcode")
    private String printAuthcode;

    @Column(name = "sale_Priceflag")
    private Long salePriceflag;

    @Column(name = "noticeinv_Flag")
    private Long noticeinvFlag;

    @Column(name = "share_Interfaceflag")
    private Long shareInterfaceflag;

    @Column(name = "finance_Dept_Flag")
    private Long financeDeptFlag;

    @Column(name = "acc_No")
    private String accNo;

    @Column(name = "org_Id_Jh")
    private String orgIdJh;

    @Column(name = "thd_Id")
    private String thdId;

    @Column(name = "org_Signature")
    private Long orgSignature;

    @Column(name = "org_Signature_Abroad")
    private Long orgSignatureAbroad;
    
    // Constructors

    /**
     * default constructor
     */
    public AbstractBasicOrg() {
    }

    /**
     * minimal constructor
     */
    public AbstractBasicOrg(Long orgId, String memberCode, String orgCode,
                            String orgName, String orgAbbreviate, String orgNodecode) {
        this.orgId = orgId;
        this.memberCode = memberCode;
        this.orgCode = orgCode;
        this.orgName = orgName;
        this.orgAbbreviate = orgAbbreviate;
        this.orgNodecode = orgNodecode;
    }

    /**
     * full constructor
     */
    public AbstractBasicOrg(Long orgId, String memberCode, String orgCode,
                            String orgParent, String orgName, String orgAbbreviate,
                            String orgPhone, String orgFax, String orgCorporation,
                            String orgAccounts, String orgBankname, String orgTanu,
                            String orgAddr, String orgRemark, Long orgIsleaf,
                            String orgNodecode, Long basicShare, String companyCode,
                            Long orgSign, Double orgSignratio, String orgMark,
                            String shareItemcode, String shareOrgcode, String printAuthcode,
                            Long salePriceflag, Long noticeinvFlag,Long shareInterfaceflag) {
        this.orgId = orgId;
        this.memberCode = memberCode;
        this.orgCode = orgCode;
        this.orgParent = orgParent;
        this.orgName = orgName;
        this.orgAbbreviate = orgAbbreviate;
        this.orgPhone = orgPhone;
        this.orgFax = orgFax;
        this.orgCorporation = orgCorporation;
        this.orgAccounts = orgAccounts;
        this.orgBankname = orgBankname;
        this.orgTanu = orgTanu;
        this.orgAddr = orgAddr;
        this.orgRemark = orgRemark;
        this.orgIsleaf = orgIsleaf;
        this.orgNodecode = orgNodecode;
        this.basicShare = basicShare;
        this.companyCode = companyCode;
        this.orgSign = orgSign;
        this.orgSignratio = orgSignratio;
        this.orgMark = orgMark;
        this.shareItemcode = shareItemcode;
        this.shareOrgcode = shareOrgcode;
        this.printAuthcode = printAuthcode;
        this.salePriceflag = salePriceflag;
        this.noticeinvFlag = noticeinvFlag;
        this.shareInterfaceflag = shareInterfaceflag;
    }

    // Property accessors

    public Long getOrgId() {
        return this.orgId;
    }

    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    public String getMemberCode() {
        return this.memberCode;
    }

    public void setMemberCode(String memberCode) {
        this.memberCode = memberCode;
    }

    public String getOrgCode() {
        return this.orgCode;
    }

    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    public String getOrgParent() {
        return this.orgParent;
    }

    public void setOrgParent(String orgParent) {
        this.orgParent = orgParent;
    }

    public String getOrgName() {
        return this.orgName;
    }

    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    public String getOrgAbbreviate() {
        return this.orgAbbreviate;
    }

    public void setOrgAbbreviate(String orgAbbreviate) {
        this.orgAbbreviate = orgAbbreviate;
    }

    public String getOrgPhone() {
        return this.orgPhone;
    }

    public void setOrgPhone(String orgPhone) {
        this.orgPhone = orgPhone;
    }

    public String getOrgFax() {
        return this.orgFax;
    }

    public void setOrgFax(String orgFax) {
        this.orgFax = orgFax;
    }

    public String getOrgCorporation() {
        return this.orgCorporation;
    }

    public void setOrgCorporation(String orgCorporation) {
        this.orgCorporation = orgCorporation;
    }

    public String getOrgAccounts() {
        return this.orgAccounts;
    }

    public void setOrgAccounts(String orgAccounts) {
        this.orgAccounts = orgAccounts;
    }

    public String getOrgBankname() {
        return this.orgBankname;
    }

    public void setOrgBankname(String orgBankname) {
        this.orgBankname = orgBankname;
    }

    public String getOrgTanu() {
        return this.orgTanu;
    }

    public void setOrgTanu(String orgTanu) {
        this.orgTanu = orgTanu;
    }

    public String getOrgAddr() {
        return this.orgAddr;
    }

    public void setOrgAddr(String orgAddr) {
        this.orgAddr = orgAddr;
    }

    public String getOrgRemark() {
        return this.orgRemark;
    }

    public void setOrgRemark(String orgRemark) {
        this.orgRemark = orgRemark;
    }

    public Long getOrgIsleaf() {
        return this.orgIsleaf;
    }

    public void setOrgIsleaf(Long orgIsleaf) {
        this.orgIsleaf = orgIsleaf;
    }

    public String getOrgNodecode() {
        return this.orgNodecode;
    }

    public void setOrgNodecode(String orgNodecode) {
        this.orgNodecode = orgNodecode;
    }

    public Long getBasicShare() {
        return this.basicShare;
    }

    public void setBasicShare(Long basicShare) {
        this.basicShare = basicShare;
    }

    public String getCompanyCode() {
        return this.companyCode;
    }

    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode;
    }

    public Long getOrgSign() {
        return this.orgSign;
    }

    public void setOrgSign(Long orgSign) {
        this.orgSign = orgSign;
    }

    public Double getOrgSignratio() {
        return this.orgSignratio;
    }

    public void setOrgSignratio(Double orgSignratio) {
        this.orgSignratio = orgSignratio;
    }

    public String getOrgMark() {
        return this.orgMark;
    }

    public void setOrgMark(String orgMark) {
        this.orgMark = orgMark;
    }

    public String getShareItemcode() {
        return this.shareItemcode;
    }

    public void setShareItemcode(String shareItemcode) {
        this.shareItemcode = shareItemcode;
    }

    public String getShareOrgcode() {
        return this.shareOrgcode;
    }

    public void setShareOrgcode(String shareOrgcode) {
        this.shareOrgcode = shareOrgcode;
    }

    public String getPrintAuthcode() {
        return this.printAuthcode;
    }

    public void setPrintAuthcode(String printAuthcode) {
        this.printAuthcode = printAuthcode;
    }

    public Long getSalePriceflag() {
        return this.salePriceflag;
    }

    public void setSalePriceflag(Long salePriceflag) {
        this.salePriceflag = salePriceflag;
    }

    public Long getNoticeinvFlag() {
        return this.noticeinvFlag;
    }

    public void setNoticeinvFlag(Long noticeinvFlag) {
        this.noticeinvFlag = noticeinvFlag;
    }

    public Long getShareInterfaceflag() {
        return shareInterfaceflag;
    }

    public void setShareInterfaceflag(Long shareInterfaceflag) {
        this.shareInterfaceflag = shareInterfaceflag;
    }

    public Long getFinanceDeptFlag() {
        return financeDeptFlag;
    }

    public void setFinanceDeptFlag(Long financeDeptFlag) {
        this.financeDeptFlag = financeDeptFlag;
    }

	public String getAccNo() {
		return accNo;
	}

	public void setAccNo(String accNo) {
		this.accNo = accNo;
	}

	public String getOrgIdJh() {
		return orgIdJh;
	}

	public void setOrgIdJh(String orgIdJh) {
		this.orgIdJh = orgIdJh;
	}

	public String getThdId() {
		return thdId;
	}

	public void setThdId(String thdId) {
		this.thdId = thdId;
	}

	public Long getOrgSignature() {
		return orgSignature;
	}

	public void setOrgSignature(Long orgSignature) {
		this.orgSignature = orgSignature;
	}

	public Long getOrgSignatureAbroad() {
		return orgSignatureAbroad;
	}

	public void setOrgSignatureAbroad(Long orgSignatureAbroad) {
		this.orgSignatureAbroad = orgSignatureAbroad;
	}

}