package org.bdp.basic.entity;

import org.bdp.basic.common.BasicConstants;
import org.bdp.basic.entity.mapper.AbstractBasicOrg;

import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Transient;

// Generated by MyEclipse Persistence Tools

/**
 * BasicOrg generated by MyEclipse Persistence Tools
 */
@Entity
@Table(name = "Basic_Org")
public class BasicOrg extends AbstractBasicOrg implements java.io.Serializable {

    /**  */
    private static final long serialVersionUID = 1L;
    @Transient
    private String orgParentName;
    /** 启用收条 0不启用 1启用 */
    @Transient
    private String orgSignStr;
    /** 销售价格控制 0不启用 1启用 */
    @Transient
    private String salePriceflagStr;
    /** 开票限制 0不启用 1启用 */
    @Transient
    private String noticeinvFlagStr;
    /** 是否启用共享接口 0不启用 1启用*/
    @Transient
    private String shareInterfaceflagStr;
    /***/
    @Transient
    private String financeDeptFlagStr;
    /** 启用指标统计（0：不启用 1：启用）*/
    @Transient
    private String orgSignatureStr;
    /** 启用境外指标统计（0：不启用 1：启用）*/
    @Transient
    private String orgSignatureAbroadStr;

    // Constructors

    /**
     * default constructor
     */
    public BasicOrg() {
    }

    /**
     * minimal constructor
     */
    public BasicOrg(Long orgId, String memberCode, String orgCode,
                    String orgName, String orgAbbreviate, String orgNodecode) {
        super(orgId, memberCode, orgCode, orgName, orgAbbreviate, orgNodecode);
    }

    /**
     * full constructor
     */
    public BasicOrg(Long orgId, String memberCode, String orgCode,
                    String orgParent, String orgName, String orgAbbreviate,
                    String orgPhone, String orgFax, String orgCorporation,
                    String orgAccounts, String orgBankname, String orgTanu,
                    String orgAddr, String orgRemark, Long orgIsleaf,
                    String orgNodecode, Long basicShare, String companyCode,
                    Long orgSign, Double orgSignratio, String orgMark,
                    String shareItemcode, String shareOrgcode, String printAuthcode,
                    Long salePriceflag, Long noticeinvFlag,Long shareInterfaceflag) {
        super(orgId, memberCode, orgCode, orgParent, orgName, orgAbbreviate,
                orgPhone, orgFax, orgCorporation, orgAccounts, orgBankname,
                orgTanu, orgAddr, orgRemark, orgIsleaf, orgNodecode,
                basicShare, companyCode, orgSign, orgSignratio, orgMark,
                shareItemcode, shareOrgcode, printAuthcode, salePriceflag,
                noticeinvFlag,shareInterfaceflag);
    }

    public String getOrgParentName() {
        /*setOrgParentName(BaseConstants.getOrgName(getOrgParent(), getMemberCode()));*/
        return orgParentName;
    }

    public void setOrgParentName(String orgParentName) {
        this.orgParentName = orgParentName;
    }

    public String getOrgSignStr() {
        setOrgSignStr("×");
        if (Long.valueOf(BasicConstants.STATE_1).equals(getOrgSign())) {
            setOrgSignStr("√");
        }
        return orgSignStr;
    }

    public void setOrgSignStr(String orgSignStr) {
        this.orgSignStr = orgSignStr;
    }

    public String getSalePriceflagStr() {
        setSalePriceflagStr("×");
        if (Long.valueOf(BasicConstants.STATE_1).equals(getSalePriceflag())) {
            setSalePriceflagStr("√");
        }
        return salePriceflagStr;
    }

    public void setSalePriceflagStr(String salePriceflagStr) {
        this.salePriceflagStr = salePriceflagStr;
    }

    public String getNoticeinvFlagStr() {
        setNoticeinvFlagStr("×");
        if (Long.valueOf(BasicConstants.STATE_1).equals(getNoticeinvFlag())) {
            setNoticeinvFlagStr("√");
        }
        return noticeinvFlagStr;
    }

    public void setNoticeinvFlagStr(String noticeinvFlagStr) {
        this.noticeinvFlagStr = noticeinvFlagStr;
    }

    public String getShareInterfaceflagStr() {
        setShareInterfaceflagStr("×");
        if(Long.valueOf(BasicConstants.STATE_1).equals(getShareInterfaceflag())){
            setShareInterfaceflagStr("√");
        }
        return shareInterfaceflagStr;
    }

    public void setShareInterfaceflagStr(String shareInterfaceflagStr) {
        this.shareInterfaceflagStr = shareInterfaceflagStr;
    }

    public String getFinanceDeptFlagStr() {
        setFinanceDeptFlagStr("");
        if(Long.valueOf(BasicConstants.STATE_1).equals(getFinanceDeptFlag())){
            setFinanceDeptFlagStr("批部门");
        }else if(Long.valueOf(BasicConstants.STATE_0).equals(getFinanceDeptFlag())){
            setFinanceDeptFlagStr("业务部门");
        }
        return financeDeptFlagStr;
    }

    public void setFinanceDeptFlagStr(String financeDeptFlagStr) {
        this.financeDeptFlagStr = financeDeptFlagStr;
    }

    public String getOrgSignatureStr() {
        setOrgSignatureStr("×");
        if (Long.valueOf(BasicConstants.STATE_1).equals(getOrgSignature())) {
            setOrgSignatureStr("√");
        }
        return orgSignatureStr;
    }

    public void setOrgSignatureStr(String orgSignatureStr) {
        this.orgSignatureStr = orgSignatureStr;
    }

    public String getOrgSignatureAbroadStr() {
        setOrgSignatureAbroadStr("×");
        if (Long.valueOf(BasicConstants.STATE_1).equals(getOrgSignatureAbroad())) {
            setOrgSignatureAbroadStr("√");
        }
        return orgSignatureAbroadStr;
    }

    public void setOrgSignatureAbroadStr(String orgSignatureAbroadStr) {
        this.orgSignatureAbroadStr = orgSignatureAbroadStr;
    }

}
